### ISSUE TITLE
Accordion content width logic

### ISSUE THREAD

**Issue by andrewreifman** [makeswift/vibes#209]
https://github.com/makeswift/vibes/blob/63934d11e79ebf9bf69473835ce07315a246938d/apps/web/vibes/soul/components/accordions/index.tsx#L49

What's the use case and point of this logic @Samantha2233?

**Comment by Samantha2233** [comment]
Hey Andrew!

This follows the Soul designs by limiting the width of the accordion content on wider screens like this: 
![Screenshot 2024-10-16 at 12 16 11 PM](https://github.com/user-attachments/assets/cc239adc-e8ed-4b47-a1d3-2d6791494563)

Then, when it's on narrower screens, the string content will take more space like this: 
![Screenshot 2024-10-16 at 12 16 17 PM](https://github.com/user-attachments/assets/c0417a6c-032f-403a-a53f-780ea8760795)

The reason I'm checking for the `typeof` the content is because the products filter panel reuses the accordion (which maybe it shouldn't?) and that content takes up the full width.
![Screenshot 2024-10-16 at 12 19 17 PM](https://github.com/user-attachments/assets/b67bb440-5d48-44b1-9054-5395df132894)

Let me know if you think we should do anything differently :)
